spring:
  cloud:
    config:
      server:
        git:
          uri: ${configserver.git.url:C:\\practise\\k8sdemo\\config}
          username: ${configserver.git.username}
          password: ${configserver.git.pass}
          clone-on-start: ${configserver.git.cloneonstart:true}
    bus:
      destination: configXchange
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

